package controller;

/**
 * The controller interface for the HTW game. The functions here have been
 * designed to give String format control to the controller, and the primary
 * operation for the controller to function, process a HTW game response to
 * different commands. Also return the output to the textView.
 * 
 * @author Daniel Zhou
 */
public interface IController {

  /**
   * Process a given string command and handle the input in controller.
   * 
   * @param command the command given (such as move to cave index)
   */
  void streamIn(String command);

  /**
   * Generate output string from the controller to text view.
   * 
   * @return StreamOutput the output String generated by the controller
   */
  String streamOut();

  /**
   * Start a Hunt The Wumpus Game.
   */
  void start();

  /**
   * Update the status of controller in response to different command received.
   */
  void update(String currentCommand);

}
